version: '2'

services:
  percona:
    image: percona/percona-server:5.7
    name: perconaserver
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306"
    volumes:
      # create volumes for use
      - /var/log/mysql
      - /var/lib/mysql
      # bind mount my local my.cnf
      # - $PWD/my.cnf:/etc/my.cnf
    command:
      # Workaround for no my.cnf in image
      - '--user=mysql'
